#!/usr/bin/env python3
import json
import argparse
import pandas as pd

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mr", required=True, help="Best MR config (json)")
    ap.add_argument("--trend", required=True, help="Best Trend config (json)")
    ap.add_argument("--meta-results", required=True, help="Meta optimization CSV")
    ap.add_argument("--out", required=True, help="Output JSON path")
    args = ap.parse_args()

    # 1. Load Inputs
    with open(args.mr) as f: mr_data = json.load(f)
    with open(args.trend) as f: tr_data = json.load(f)
    df = pd.read_csv(args.meta_results)
    
    # Pick best ADX threshold (highest final_btc)
    best_row = df.sort_values("final_btc", ascending=False).iloc[0]
    best_adx = float(best_row["adx_threshold"])

    # Extract Strategy blocks
    mr_strat = mr_data.get("strategy", mr_data)
    tr_strat = tr_data.get("strategy", tr_data)

    # 2. Build V2 Structure
    config = {
        "fees": {
            "maker_fee": 0.0002,
            "taker_fee": 0.0004,
            "slippage_bps": 1.0,
            "bnb_discount": 0.25,
            "pay_fees_in_bnb": True
        },
        "strategy": {
            "strategy_type": "meta",
            "adx_threshold": best_adx,
            "bar_interval_minutes": 15,
            
            # --- NESTED OVERRIDES ---
            "mean_reversion_overrides": {
                "comment": "Optimized MR Settings",
                **mr_strat # Unpack all MR params here
            },
            "trend_overrides": {
                "comment": "Optimized Trend Settings",
                **tr_strat # Unpack all Trend params here
            }
        },
        "execution": {
            "exchange_type": "futures",  # Set to futures for BTC trading
            "leverage": 1,
            "interval": "15m",
            "poll_sec": 5,
            "ttl_sec": 30,
            "taker_fallback": True,
            "max_taker_btc": 0.002,
            "max_spread_bps_for_taker": 2.0,
            "min_trade_frac": 0.0015,
            "min_trade_floor_btc": 0.0,
            "min_trade_cap_btc": 0.0,
            "min_trade_btc": 0.0001
        },
        "risk": {
            "basis_btc": 1.0,
            "risk_mode": "dynamic",
            "max_dd_frac": 0.20,
            "drawdown_reset_days": 7.0,   # Wait 7 days after crash
            "drawdown_reset_score": 30.0  # Restart only if ADX > 30
        }
    }

    # 3. Clean up keys that shouldn't be in overrides
    # (Optional: remove metadata keys generated by wf_pick)
    for block in [config["strategy"]["mean_reversion_overrides"], config["strategy"]["trend_overrides"]]:
        for k in ["_generated_by", "_generated_at", "_family", "strategy_type"]:
            block.pop(k, None)

    # 4. Save
    with open(args.out, "w") as f:
        json.dump(config, f, indent=2)
    
    print(f"Generated V2 Config: {args.out}")
    print(f"Selected ADX Threshold: {best_adx}")

if __name__ == "__main__":
    main()